quotes = ["It is customary to kneel when surrendering to a king",
          "I'm not so easily killed, men have been trying for years",
          "She's my daughter, you will not strike her",
          "Fewer.",
          "A good act does not wash out the bad nor the bad the good.",
          "I don't punish men for bravery, I reward them.",
          "I will not become a page in someone else's history book",
          "Cleaner ways don't win wars",
          "We march to victory or defeat but we go forward, only forward.",
          "COME WITH ME AND TAKE THIS CITY",
          "I never asked for this, no more than I asked to be king. Yet dare I disregard her? We do not choose our destinies. Yet we must ... we must do our duty, no? Great or small, we must do our duty.",
          "It is not a question of wanting. The throne is mine, as Robert's heir. That is law. After me, it must pass to my daughter, unless Selyse should finally give me a son.",
          "Good men and true will fight for Joffrey, wrongly believing him the true king. A northman might even say the same of Robb Stark. But these lords who flocked to my brother's banners knew him for a usurper.",
          "Kings have no friends, only subjects and enemies.",
          "I know the cost! Last night, gazing into that hearth, I saw things in the flames as well. I saw a king, a crown of fire on his brows, burning… burning, {}. His own crown consumed his flesh and turned him into ash. Do you think I need Melisandre to tell me what that means? Or you?",
          "I never asked for this crown. Gold is cold and heavy on the head, but so long as I am the king, I have a duty... If I must sacrifice one child to the flames to save a million from the dark... Sacrifice... is never easy",
          "We are well rid of her, then. I will not suffer such abominations here. This is not King's Landing.",
          "Lord Seaworth is a man of humble birth, but he reminded me of my duty, when all I could think of was my rights. I had the cart before the horse, {} said. I was trying to win the throne to save the kingdom, when I should have been trying to save the kingdom to win the throne",
          "Half my army is made up of unbelievers, I will have no burnings, pray harder.",
          "Everyman shall reap what he has sown, from the highest lord to the lowest gutter rat. And some will lose more than the tips of their fingers, I promise you. They have made my kingdom bleed, I do not forget that.",
          "It has always been so. I am not . . . I am not a cruel man, Ser {}. You know me. Have known me long. This is not my decree. It has always been so, since Aegon's day and before. Daemon Blackfyre, the brothers Toyne, the Vulture King, Grand Maester Hareth . . . traitors have always paid with their lives . . . even Rhaenyra Targaryen. She was daughter to one king and mother to two more, yet she died a traitor's death for trying to usurp her brother's crown. It is law. Law, {}. Not cruelty.",
          "I defeated your uncle Victarion and his Iron Fleet off Fair Isle, the first time your father crowned himself. I held Storm's End against the power of the Reach for a year, and took Dragonstone from the Targaryens. I smashed Mance Rayder at the Wall, though he had twenty times my numbers. Tell me, turncloak, what battles has the Bastard of Bolton ever won that I should fear him?",
          "We all know what my brother would do. Robert would gallop up to the gates of Winterfell alone, break them with his warhammer, and ride through the rubble to slay Roose Bolton with his left hand and the Bastard with his right. I am not Robert. But we will march, and we will free Winterfell … or die in the attempt.",
          "When I was a lad I found an injured goshawk and nursed her back to health. Proudwing, I named her. She would perch on my shoulder and flutter from room to room after me and take food from my hand, but she would not soar. Time and again I would take her hawking, but she never flew higher than the treetops.",
          "If Renly had done his duty as a brother we would have smashed lord Tywin together. A victory even Robert would have been proud of.",
          "Any of you I would think, even the cook. ",
          "Without a son of Winterfell to stand beside me, I can only hope to win the north by battle. That requires stealing a leaf from my brother's book. Not that Robert ever read one.",
          "I am king. Wants do not enter into it. I have a duty to my daughter. To the realm. Even to Robert. He loved me but little, I know, yet he was my brother.",
          "I mean to scour that court clean. As Robert should have done after the Trident."]
